# Generated by Django 5.0.6 on 2024-06-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_spare_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.FloatField(choices=[(1.0, 'Метры'), (0.3048, 'Футы'), (0.9144, 'Ярда')])),
            ],
        ),
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['rubric'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
