# Generated by Django 4.2.13 on 2024-08-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_author_book_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
